# Configuración del modelo PD (Probability of Default)
model:
  name: "pd_model"
  type: "classification"
  algorithm: "xgboost"  # xgboost, lightgbm, catboost
  
  # Parámetros del modelo
  hyperparameters:
    n_estimators: 1000
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1
    reg_lambda: 1.0
    random_state: 42
    n_jobs: -1
    
  # Cross-validation
  cv:
    n_splits: 5
    stratify: true
    random_state: 42

# Features engineering
features:
  target_variable: "default_flag"
  
  # Features categóricas
  categorical_features:
    - "grade"
    - "sub_grade" 
    - "emp_title"
    - "emp_length"
    - "home_ownership"
    - "verification_status"
    - "issue_d"
    - "loan_status"
    - "pymnt_plan"
    - "purpose"
    - "addr_state"
    - "earliest_cr_line"
    - "initial_list_status"
    - "application_type"
    
  # Features numéricas
  numerical_features:
    - "loan_amnt"
    - "funded_amnt"
    - "funded_amnt_inv"
    - "term"
    - "int_rate"
    - "installment"
    - "annual_inc"
    - "dti"
    - "delinq_2yrs"
    - "fico_range_low"
    - "fico_range_high"
    - "inq_last_6mths"
    - "mths_since_last_delinq"
    - "mths_since_last_record"
    - "open_acc"
    - "pub_rec"
    - "revol_bal"
    - "revol_util"
    - "total_acc"
    - "out_prncp"
    - "out_prncp_inv"
    - "total_pymnt"
    - "total_pymnt_inv"
    - "total_rec_prncp"
    - "total_rec_int"
    - "total_rec_late_fee"
    - "recoveries"
    - "collection_recovery_fee"
    - "last_pymnt_amnt"
    - "collections_12_mths_ex_med"
    - "mths_since_last_major_derog"
    - "policy_code"
    - "acc_now_delinq"
    - "tot_coll_amt"
    - "tot_cur_bal"
    - "open_acc_6m"
    - "open_act_il"
    - "open_il_12m"
    - "open_il_24m"
    - "mths_since_rcnt_il"
    - "total_bal_il"
    - "il_util"
    - "open_rv_12m"
    - "open_rv_24m"
    - "max_bal_bc"
    - "all_util"
    - "total_rev_hi_lim"
    - "inq_fi"
    - "total_cu_tl"
    - "inq_last_12m"

# Data processing
data:
  train_size: 0.7
  val_size: 0.15
  test_size: 0.15
  random_state: 42
  
  # Handling missing values
  missing_strategy:
    numerical: "median"  # mean, median, mode
    categorical: "mode"
    
  # Outlier handling
  outlier_method: "iqr"  # iqr, zscore, isolation_forest
  outlier_threshold: 1.5

# Métricas de evaluación
metrics:
  primary: "roc_auc"
  secondary:
    - "precision"
    - "recall"
    - "f1_score"
    - "accuracy"
    - "log_loss"
    - "brier_score"
    
  # Métricas específicas de riesgo
  risk_metrics:
    - "gini_coefficient"
    - "ks_statistic" 
    - "information_value"
    - "population_stability_index"
    - "concordance_ratio"

# Monitoreo y drift
monitoring:
  enable_drift_detection: true
  reference_period: "2023-01-01"
  monitoring_period: "2024-01-01"
  drift_threshold: 0.1
  
# Explainability
explainability:
  enable_shap: true
  enable_lime: false
  enable_eli5: false
  max_features_display: 20

# Regulatorio - SAR
regulatory:
  sar_compliance: true
  documentation_level: "full"  # basic, standard, full
  backtesting_window: 12  # meses
  stress_testing: true